FROM cartesi-lambada:1.0
RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    curl \
    git \
    build-essential
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
WORKDIR /app
COPY Cargo.toml ./
RUN mkdir src
COPY src ./src
RUN cargo clean && cargo build --release
CMD ["./target/release/subscribe-celestia-blocks"]
