FROM rust:latest
RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    pkg-config \
    libssl-dev \
    cmake \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*
ENV RUST_BACKTRACE=1
ENV PROTOC=/usr/bin/protoc
WORKDIR /app
COPY ./Cargo.toml ./
COPY src ./src
RUN cargo build
CMD ["./target/debug/subscribe-celestia-blocks"]
