
FROM rust:latest

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev

WORKDIR /usr/src/subscribe-celestia-blocks

COPY ./Cargo.toml ./

RUN mkdir src && \
    echo "fn main() {println!(\"if you see this, the build broke:((\")}" > src/main.rs

RUN cargo build --release

RUN rm -f ./target/release/deps/subscribe-celestia-blocks*
RUN rm src/*.rs
COPY ./src ./src

RUN cargo build --release

CMD ["./target/release/subscribe-celestia-blocks"]
