FROM runonflux/celestia-node:latest
RUN mkdir -p /home/celestia/.celestia-bridge && \
    chmod +x /home/celestia/.celestia-bridge

WORKDIR /home/celestia

CMD ["celestia", "light", "start", "--core.ip", "consensus.lunaroasis.net", "--keyring.accname", "cel-name-my"]
