version: '3.8'

services:
  rust-app1:
    build:
      context: .
      dockerfile: Dockerfile-rust1
    environment:
      - ETHEREUM_NODE_URL=http://anvil:8545
      - CELESTIA_NODE_URL=http://celestia-node:26658
      - DB_PATH=/data/db
    depends_on:
      - celestia-node
      - anvil
    volumes:
      - ./rust-app1-data:/data/db
    networks:
      - blockchain-network
    command: ["tail", "-f", "/dev/null"]

  rust-app2:
    build:
      context: .
      dockerfile: Dockerfile-rust2
    environment:
      - ETHEREUM_NODE_URL=http://anvil:8545
      - CELESTIA_NODE_URL=http://celestia-node:26658
      - DB_PATH=/data/db
    depends_on:
      - celestia-node
      - anvil
    volumes:
      - ./rust-app2-data:/data/db
    networks:
      - blockchain-network
    command: ["tail", "-f", "/dev/null"]

  celestia-node:
    build:
      context: .
      dockerfile: Dockerfile-celestia
    volumes:
      - ./config:/home/celestia/.celestia-bridge
    command: ["celestia", "light", "start", "--core.ip", "consensus.lunaroasis.net", "--keyring.accname", "cel-name-my"]
    ports:
      - "26658:26658"
    networks:
      - blockchain-network

  anvil:
    build:
      context: .
      dockerfile: Dockerfile-anvil
    command: ["anvil", "--host", "0.0.0.0"]
    ports:
      - "8545:8545"
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge
