FROM cartesi-lambada:1.0

RUN apt-get update && apt-get install -y \
    protobuf-compiler \
    curl \
    git \
    build-essential \
    libssl-dev \
    pkg-config \
    cmake \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
ENV PROTOC=/usr/bin/protoc
ENV RUST_BACKTRACE=1

WORKDIR /app

RUN git clone https://github.com/nyakiomaina/celestia-example.git /app

RUN cargo build

CMD ["./target/debug/subscribe-celestia-blocks"]
