FROM rust:latest
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/nyakiomaina/celestia-example.git /app
WORKDIR /app
RUN cargo build --release
CMD ["./target/release/celestia-example"]
