name: rust fmt check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install/update rustfmt
      run: |
        rustup update
        rustup component add rustfmt
    - name: Check formatting
      run: cargo fmt -- --check

    - name: Check formatting in subscribe-avail directory
      run: |
        cd subscribe-avail
        cargo fmt -- --check

    - name: Check formatting in subscribe-celestia directory
      run: |
        cd subscribe-celestia
        cargo fmt -- --check

    - name: Check formatting in subscribe-espresso directory
      run: |
        cd subscribe-espresso
        cargo fmt -- --check

    - name: Check formatting in subscribe-evm-blocks directory
      run: |
        cd subscribe-evm-blocks
        cargo fmt -- --check

    - name: Check formatting in subscribe-evm-da directory
      run: |
        cd subscribe-evm-da
        cargo fmt -- --check

    - name: Check formatting in subscribe-celestia-blocks directory
      run: |
        cd subscribe-celestia-blocks
        cargo fmt -- --check
